name: PyKUHC
main: fr.paramystick.PyKUHC.PyKUHC
version: 1.0
description: >
             Le plugin UHC fait par la team ParamYsticK !
commands:
  timer:
    description: gestion du timer !
    usage: |
           /timer <seconde(s)>
           /timer <stop/start>
           Exemple: /timer 30 - Initialise le compte à rebour à 30 secondes.
                         /timer start - Démarre le compte à rebour.
                         /timer stop - Arrête le compte à rebour.
  equipe:
    description: gestion des équipe !
    usage : |
           /equipe <active/desactive>
           /equipe <set> <joueur par equipe>
           /equipe <quit>
           /equipe <list>
           Exemple: /equipe set 3 - initialise les équipe à 3 joueurs.
                         /equipe active - démarre le système d'équipe.
                         /equipe desactive - désactive le système d'équipe = 1 vs tous.
                         /equipe join rouge - rejoins l'équipe rouge
                         /equipe quit - vous ne faites plus partie d'aucune équipe.