name: PyKUHC
main: fr.paramystick.PyKUHC.PyKUHC
version: 1.0
description: >
             Le plugin UHC fait par la team ParamYsticK !
commands:
  timer:
    description: Lance un timer avec le temps desire !
    usage: |
           /timer <seconde(s)>
           /timer <stop/start>
           Exemple: /timer 30 - initialise le compte a rebour a 30 secondes.
                       /timer start demarre le compte a rebour.
                       /timer stop arrete le compte a rebour.